//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PropertyManagerApp.rc
//
#define IDS_MAP_TOOLBAR                 1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_NAVIGATOR_BAR                101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_PropertyManagerTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define IDR_PASTE_MENU                  151
#define ID_PROPERTIES1                  152
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
 

 
#define ID_VIEW_NAVIGATION              185  
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDR_MAP                         254
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_FORM                        310 
#define IDD_LIST_MAIN                   311
#define IDD_BKGND                       312
#define IDI_FWD                         316
#define IDI_GO                          318
#define IDI_EDIT                        319
#define IDI_MANAGER                     320
#define IDI_FAMILY                      321 
#define IDI_REPAIR_INFO                 322
#define IDI_REPAIR_MGR                  323
#define IDI_EDIT1                       324
#define IDI_MEMBER                      325
#define IDI_HOUSE                       326
#define IDD_TABLE                       327
#define IDD_LOGIN                       328
#define IDD_DIALOG2                     334
#define IDD_LIST_PANE                   334
#define IDD_DIALOG3                     335
#define IDD_LIST                        336
#define IDD_DIALOG4                     337
#define IDD_BKGND_MAIN                  337
#define IDD_BKGND_OP                    338
#define IDD_BKGND_GROUP                 339
#define IDD_BKGND_USER                  340
#define IDI_GRADE                       342
#define IDD_LIST_INCOME_RECORD          342
#define IDI_USERS                       343
#define IDD_LIST_REPAIR                 343
#define IDI_OPS                         344
#define IDD_LIST_REPAIR_SUM             344
#define IDD_LIST_MATERIAL_REC           345
#define IDI_ICON1                       346
#define IDI_OK                          346
#define IDD_LIST_MEMBER_REC             346
#define IDI_PWD                         347
#define IDD_LIST_DEPART_REC             347
#define IDI_ICON2                       348
#define IDI_BKGND                       348
#define IDD_LIST_PROPOWNER              348
#define IDD_LIST_RECEIPT_SUMUP_QUERY    349
#define IDD_LIST_EXPECT_SUMUP_QUERY     350
#define IDI_ADD                         350
#define IDD_LIST_STATE_CHART            351
#define IDI_DEL                         351
#define IDI_LOGIN                       352
#define IDD_LIST_RECEIPT_DETAILS_QUERY  352
#define IDD_LIST_EXPECT_ACCOUNT         353
#define IDD_LIST_SUMUP_REPORT           354
#define IDD_BKGND_LVL                   355
#define IDI_ICON3                       356
#define IDI_MANAGERS                    356
#define IDI_ICON4                       357
#define IDI_RESET                       357
#define IDR_EMPTY                       358
#define IDI_ICON5                       362
#define IDI_PRINTER                     362
#define IDI_CFG                         363
#define IDD_WORKER                      364
#define ID_MAP_MODE                     511
#define ID_LIST_MODE                    512
#define ID_ENGINEER_MODE                513
#define ID_BKGND_MANAGER                514
#define IDS_BUILDING                    520
#define IDS_WAY                         521
#define IDS_GREEN                       522
#define IDS_ELECTRONIC                  523
#define IDS_WATER                       524
#define IDS_WARM                        525
#define IDS_OTHER                       526
#define IDS_NAVIGATOR                   527
#define IDS_MENUBAR                     528
#define IDS_STANDARD                    529
#define IDS_MAP                         530
#define IDC_STC_DAILY                   1000
#define IDC_BTN_LIST_INCOME_RECORD      1001
#define IDC_BTN_LIST_REPAIR             1002
#define IDC_BTN_LIST_REPAIR_SUM         1003
#define IDC_COMMAND1                    1004
#define IDC_BTN_LIST_RECEIPT_SUMUP_QUERY 1004
#define IDC_BTN_REPAIR_SUM2             1005
#define IDC_STC_BUTTON1                 1005
#define IDC_BTN_LIST_MATERIAL_REC       1006
#define IDC_BTN_LIST_MEMBER_REC         1007
#define IDC_BTN_LIST_DEPART_REC         1008
#define IDC_BTN_LIST_PROPOWNER          1009
#define IDC_COMMAND2                    1010
#define IDC_BTN_LIST_EXPECT_SUMUP_QUERY 1010
#define IDC_COMMAND3                    1011
#define IDC_BTN_LIST_STATE_CHART        1011
#define IDC_COMMAND4                    1012
#define IDC_BTN_LIST_RECEIPT_DETAILS_QUERY 1012
#define IDC_COMMAND5                    1013
#define IDC_BTN_LIST_EXPECT_ACCOUNT     1013
#define IDC_COMMAND6                    1014
#define IDC_BTN_LIST_SUMUP_REPORT       1014
#define IDC_STC_BUTTON2                 1015
#define IDC_STC_BUTTON3                 1016
#define IDC_STC_BUTTON4                 1017
#define IDC_BTN_LIST_MAIN               1018
#define IDC_STC_LINE                    1019
#define IDC_TABLE                       1020
#define IDC_EDIT_PWD                    1022
#define IDC_CHK_SAVE_PWD                1023
#define IDC_EDIT_PWD2                   1023
#define IDC_CHK_AUTO_LOGIN              1024
#define IDC_EDIT_OLD_PWD                1024
#define IDC_CB_NAME                     1025
#define IDC_EDIT1                       1029
#define IDC_EDIT_ADDR                   1029
#define IDC_MARK                        1030
#define IDC_CHK_EXPAND                  1031
#define IDC_TREE_CMD                    1039
#define IDC_TREE_DETAILS                1040
#define IDC_BTN_CMD                     1041
#define IDC_BTN_BKGNDMAIN               1041
#define IDC_BTN_DETAILS                 1042
#define IDC_BTN_OPMGR                   1042
#define IDC_BTN_GROUPMGR                1043
#define IDC_BTN_USERMGR                 1044
#define IDC_STC_MAIN                    1046
#define IDC_BTN_LVLMGR                  1048
#define IDC_EDIT_NAME                   1049
#define IDC_CHK_CHANGE_PWD              1050
#define IDC_STC_NAME                    1051
#define IDC_STC_NAME2                   1052
#define IDC_STC_GRADE                   1052
#define IDC_EDIT_GRADE                  1053
#define IDC_STC_PWD                     1054
#define IDC_STC_PWD2                    1055
#define IDC_STC_PWD3                    1056
#define IDC_CHK_SUBMIT                  1057
#define IDC_BTN_SUBMIT                  1057
#define IDC_STC_OP                      1058
#define IDC_LIST_OP                     1060
#define IDC_EDIT_GRADE2                 1061
#define IDC_EDIT_GROUP                  1061
#define IDC_ADMIN_LIST                  1066
#define IDC_STC_ADMIN                   1067
#define IDC_LIST                        1068
#define IDC_LIST_GROUP                  1068
#define IDC_OP_LIST                     1069
#define IDC_STC_OPS2                    1069
#define IDC_OP_LIST2                    1070
#define IDC_STC_MAIN2                   1071
#define IDC_STC_OPS                     1072
#define IDC_LIST_USER                   1072
#define IDC_STC_USER                    1073
#define IDC_STC_GROUP                   1074
#define IDC_CHK_MGR                     1076
#define IDC_CHK_GROUP                   1077
#define IDC_BUTTON1                     1077
#define IDC_BTN_STC                     1077
#define IDC_BTN_TEST                    1077
#define IDC_BTN_PRINT                   1077
#define IDC_CHK_USER                    1078
#define IDC_CHK_OP                      1079
#define IDC_LIST1                       1081
#define IDC_STC_TITLE                   1083
#define IDC_PROGRESS1                   1084
#define IDC_PROGRESS                    1084
#define IDC_STC1                        1085
#define IDC_STC2                        1086
#define IDC_STC3                        1087
#define IDC_STC4                        1088
#define ID_MAP_NON                      32772
#define ID_MAP_ZOOMOUT                  32773
#define ID_MAP_ZOOMIN                   32774
#define ID_MAP_ZOOMFIT                  32775
#define ID_MAP_ZOOMRESET                32776
#define ID_MAP_GAUGE                    32777
#define ID_MAP_ERASE                    32778
#define ID_OPTION                       32781
#define ID_SYSCFG                       32782
#define ID_OPTIONS                      32783
#define ID_LIST_PROJECT		32660
#define ID_LIST_ZONE		32661
#define ID_LIST_BLOCK		32662
#define ID_LIST_APARTMENT	32663
#define ID_LIST_HOME		32664


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        365
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
