//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MMShow.rc
//
#define IDOK2                           2
#define IDCANCEL2                       3
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MMSHOW_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_WEBBROWSER                  130
#define IDD_MIDEAPLAYER                 132
#define IDD_PIC                         133
#define IDD_LIVE_SRC                    134
#define IDD_VIDEO_SRC                   135
#define IDR_MENU_MAIN                   136
#define IDD_PREVIEW                     138
#define IDD_LIVE_CHILD                  139
#define IDD_OUTPUT                      140
#define IDD_PROGRAM                     141
#define IDD_PPROGRAMITEM                142
#define IDD_DSHOW                       143
#define IDR_ACCELERATOR                 144
#define IDD_CFG                         145
#define IDD_CFG_CAMERA                  146
#define IDD_CFG_RECORD                  147
#define IDD_CFG_OUTPUT                  148
#define IDD_CFG_UI                      149
#define IDD_DIALOG1                     150
#define IDD_LIST_CONFORM                150
#define IDD_LIST_CONFIRM                150
#define IDD_INST_OUTPUT_CFG             152
#define IDC_EDIT_DESC                   1000
#define IDC_LIST_PROGRAM                1001
#define IDC_STC_PROGRAM_NAME            1002
#define IDC_BTN_SELECT                  1003
#define IDC_BTN_ADD                     1004
#define IDC_BTN_PROP                    1005
#define IDC_BTN_STEP                    1005
#define IDC_BTN_DEL                     1007
#define IDC_BTN_UP                      1008
#define IDC_BTN_DOWN                    1011
#define IDC_STC_PREVIEW                 1012
#define IDC_CHK_PREVIEW                 1015
#define IDC_CB_VIDEO_OUTPUT             1016
#define IDC_CHK_CURSOR                  1017
#define IDC_CHK_GAUGE                   1018
#define IDC_BTN_CLEAR                   1019
#define IDC_CHK_TRASPARENT_GAUGE        1019
#define IDC_STC_VIDEO                   1023
#define IDC_BTN_SELECT_FILE             1024
#define IDC_TAB                         1027
#define IDC_CB_HISTORY                  1028
#define IDC_BTN_GO                      1029
#define IDC_BTN_NEXT                    1030
#define IDC_BTN_FORWORD                 1030
#define IDC_BTN_BACK                    1031
#define IDC_BTN_BACKWARD                1031
#define IDC_BTN_STOP                    1032
#define IDC_STC_CONTENT                 1033
#define IDC_BTN_SKIP_BACK               1033
#define IDC_BTN_SKIP_BACKWARD           1033
#define IDC_STC_VIDEO_SRC               1034
#define IDC_BTN_SKIP_FORWORD            1034
#define IDC_STC_CONTENT2                1034
#define IDC_CHK_PLAY                    1035
#define IDC_STC_CONTENT3                1035
#define IDC_BTN_NEXT2                   1035
#define IDC_BTN_ZOOM                    1035
#define IDC_SLD_PROGRESS                1036
#define IDC_STC_GAUGE                   1037
#define IDC_SLD_VOLUME                  1038
#define IDC_STC_CAPTION                 1043
#define IDC_STC_BIG                     1044
#define IDC_STC_SMALL                   1045
#define IDC_STC_SMALL2                  1046
#define IDC_STC_LIVE                    1046
#define IDC_STC_OUTPUT                  1047
#define IDC_STC_PROGRAM                 1048
#define IDC_BTN_RECORD                  1049
#define IDC_EDIT_REC_PATH               1050
#define IDC_EDIT_NAME                   1050
#define IDC_EDIT_FOLDER                 1050
#define IDC_BTN_SEL_REC_FILE            1051
#define IDC_EDIT_PATH                   1051
#define IDC_CB_CAM                      1052
#define IDC_RD_PREVIEW                  1055
#define IDC_RD_DSHOW                    1056
#define IDC_RD_VIDEO_FILE               1056
#define IDC_RD_WEBPAGE                  1057
#define IDC_RD_DSHOW2                   1057
#define IDC_STC_RECORDING               1062
#define IDC_STC_TIP                     1063
#define IDC_LIST_CONTENT                1064
#define IDC_SLD                         1065
#define IDC_SLD_ZOOM                    1065
#define IDC_BUTTON1                     1066
#define IDC_BTN_CFG                     1066
#define IDC_SLIDER1                     1067
#define IDC_CHK_MUTE                    1068
#define IDC_CHECK1                      1069
#define IDC_CHK_DEFAULT                 1069
#define IDC_STATIC1                     1070
#define IDC_CB_CAM2                     1073
#define IDC_CB_VIDEO_SIZE               1073
#define IDC_CB_CAM3                     1074
#define IDC_CB_SIZE                     1075
#define IDC_CB_AUDIO_BITRATE            1076
#define IDC_CB_AUDIO_SAMPLE_RATE        1077
#define IDC_CB_VIDEO_BITRATE            1078
#define IDC_CB_AUDIO_BITRATE2           1078
#define IDC_CB_VIDEO_WIDTH              1079
#define IDC_BUTTON2                     1079
#define IDC_CB_FPS                      1080
#define IDC_BUTTON3                     1080
#define IDC_CB_VIDEO_HEIGHT             1081
#define IDC_BUTTON4                     1081
#define IDC_CB_FORMAT                   1082
#define IDC_BUTTON5                     1082
#define IDC_BUTTON6                     1083
#define IDC_CB_DEF_OPRATED              1084
#define IDC_BUTTON7                     1084
#define IDC_CHK_SAVE_HISTORY            1085
#define IDC_BUTTON8                     1085
#define IDC_DEF_PREVIEW                 1086
#define IDC_BUTTON9                     1086
#define IDC_CB_DEF_CAM                  1087
#define IDC_CB_DEF_AUDIO_INPUT          1088
#define IDC_CB_DEF_AUDIO_OUTPUT         1089
#define IDC_CHK_SHOW_CURSOR             1089
#define IDC_CB_DEF_VIDEO_INPUT          1090
#define IDC_CHK_SHOW_CURSOR2            1090
#define IDC_CB_DEF_VIDEO_OUTPUT         1091
#define IDM_NEW_THIS                    32790
#define IDM_RELOAD_THIS                 32791
#define IDM_OPEN_THIS                   32792
#define IDM_SAVEAS_THIS                 32793
#define IDM_PROP_THIS                   32794
#define IDM_SAVE_THIS                   32795
#define IDM_OPTION_THIS                 32805
#define IDM_ABOUT_THIS                  32806
#define IDM_EXIT_THIS                   32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
